using System;

namespace CallRecordInsights.Models
{
    public interface IKustoCallRecord
    {
        string CallRecordTenantIdContext { get; set; }
        Guid? CallId { get; set; }
        Guid? SessionId { get; set; }
        string? StreamId { get; set; }
        string? StreamDirection { get; set; }
        string? MediaLabel { get; set; }
        DateTimeOffset? CallStartTime { get; set; }
        DateTimeOffset? CallEndTime { get; set; }
        DateTimeOffset? SessionStartTime { get; set; }
        DateTimeOffset? SessionEndTime { get; set; }
        DateTimeOffset? LastModifiedDateTimeOffset { get; set; }
        string? CallType { get; set; }
        string? JoinWebUrl { get; set; }
        string? VideoCodec { get; set; }
        string? AudioCodec { get; set; }
        bool? WasMediaBypassed { get; set; }
        string? FailureStage { get; set; }
        string? FailureReason { get; set; }
        long? PacketUtilization { get; set; }
        long? AverageBandwidthEstimate { get; set; }
        TimeSpan? AverageJitter { get; set; }
        TimeSpan? MaxJitter { get; set; }
        TimeSpan? AverageRoundTripTime { get; set; }
        TimeSpan? MaxRoundTripTime { get; set; }
        TimeSpan? AverageAudioNetworkJitter { get; set; }
        TimeSpan? MaxAudioNetworkJitter { get; set; }
        double? AverageAudioDegradation { get; set; }
        double? AveragePacketLossRate { get; set; }
        double? MaxPacketLossRate { get; set; }
        double? PostForwardErrorCorrectionPacketLossRate { get; set; }
        double? AverageRatioOfConcealedSamples { get; set; }
        double? MaxRatioOfConcealedSamples { get; set; }
        double? LowVideoProcessingCapabilityRatio { get; set; }
        double? AverageVideoFrameRate { get; set; }
        double? AverageReceivedFrameRate { get; set; }
        double? LowFrameRateRatio { get; set; }
        double? AverageVideoPacketLossRate { get; set; }
        double? AverageVideoFrameLossPercentage { get; set; }
        string? Organizer_UserDisplayName { get; set; }
        Guid? Organizer_UserId { get; set; }
        Guid? Organizer_UserTenantId { get; set; }
        string? Organizer_ApplicationInstanceDisplayName { get; set; }
        Guid? Organizer_ApplicationInstanceId { get; set; }
        Guid? Organizer_ApplicationInstanceTenantId { get; set; }
        string? Organizer_GuestDisplayName { get; set; }
        Guid? Organizer_GuestId { get; set; }
        Guid? Organizer_GuestTenantId { get; set; }
        string? Organizer_PhoneDisplayName { get; set; }
        string? Organizer_PhoneId { get; set; }
        Guid? Organizer_PhoneTenantId { get; set; }
        string? Organizer_OnPremisesDisplayName { get; set; }
        Guid? Organizer_OnPremisesId { get; set; }
        Guid? Organizer_OnPremisesTenantId { get; set; }
        string? Organizer_EncryptedDisplayName { get; set; }
        Guid? Organizer_EncryptedId { get; set; }
        Guid? Organizer_EncryptedTenantId { get; set; }
        string? Organizer_AcsUserDisplayName { get; set; }
        Guid? Organizer_AcsUserId { get; set; }
        Guid? Organizer_AcsUserTenantId { get; set; }
        string? Organizer_SpoolUserDisplayName { get; set; }
        Guid? Organizer_SpoolUserId { get; set; }
        Guid? Organizer_SpoolUserTenantId { get; set; }
        string? Organizer_AcsApplicationInstanceDisplayName { get; set; }
        Guid? Organizer_AcsApplicationInstanceId { get; set; }
        Guid? Organizer_AcsApplicationInstanceTenantId { get; set; }
        string? Organizer_SpoolApplicationInstanceDisplayName { get; set; }
        Guid? Organizer_SpoolApplicationInstanceId { get; set; }
        Guid? Organizer_SpoolApplicationInstanceTenantId { get; set; }
        string? Organizer_Id { get; set; }
        string? Organizer_UserPrincipalName { get; set; }
        string? Organizer_DisplayName { get; set; }
        Guid? Organizer_TenantId { get; set; }
        string? Organizer_IdType { get; set; }
        string? Callee_UserDisplayName { get; set; }
        Guid? Callee_UserId { get; set; }
        Guid? Callee_UserTenantId { get; set; }
        string? Callee_ApplicationInstanceDisplayName { get; set; }
        Guid? Callee_ApplicationInstanceId { get; set; }
        Guid? Callee_ApplicationInstanceTenantId { get; set; }
        string? Callee_GuestDisplayName { get; set; }
        Guid? Callee_GuestId { get; set; }
        Guid? Callee_GuestTenantId { get; set; }
        string? Callee_PhoneDisplayName { get; set; }
        string? Callee_PhoneId { get; set; }
        Guid? Callee_PhoneTenantId { get; set; }
        string? Callee_OnPremisesDisplayName { get; set; }
        Guid? Callee_OnPremisesId { get; set; }
        Guid? Callee_OnPremisesTenantId { get; set; }
        string? Callee_EncryptedDisplayName { get; set; }
        Guid? Callee_EncryptedId { get; set; }
        Guid? Callee_EncryptedTenantId { get; set; }
        string? Callee_AcsUserDisplayName { get; set; }
        Guid? Callee_AcsUserId { get; set; }
        Guid? Callee_AcsUserTenantId { get; set; }
        string? Callee_SpoolUserDisplayName { get; set; }
        Guid? Callee_SpoolUserId { get; set; }
        Guid? Callee_SpoolUserTenantId { get; set; }
        string? Callee_AcsApplicationInstanceDisplayName { get; set; }
        Guid? Callee_AcsApplicationInstanceId { get; set; }
        Guid? Callee_AcsApplicationInstanceTenantId { get; set; }
        string? Callee_SpoolApplicationInstanceDisplayName { get; set; }
        Guid? Callee_SpoolApplicationInstanceId { get; set; }
        Guid? Callee_SpoolApplicationInstanceTenantId { get; set; }
        string? Callee_Id { get; set; }
        string? Callee_UserPrincipalName { get; set; }
        string? Callee_DisplayName { get; set; }
        Guid? Callee_TenantId { get; set; }
        string? Callee_IdType { get; set; }
        string? Callee_EndpointType { get; set; }
        string? Callee_ProductFamily { get; set; }
        string? Callee_Platform { get; set; }
        string? Callee_UserAgentHeaderValue { get; set; }
        string? Callee_ServiceRole { get; set; }
        string? Callee_ApplicationVersion { get; set; }
        Guid? Callee_AzureAdAppId { get; set; }
        Guid? Callee_CommunicationServiceId { get; set; }
        string? Callee_ConnectionType { get; set; }
        string? Callee_ReflexiveIPAddress { get; set; }
        string? Callee_Subnet { get; set; }
        string? Callee_IpAddress { get; set; }
        string? Callee_MacAddress { get; set; }
        long? Callee_LinkSpeed { get; set; }
        string? Callee_NetworkTransportProtocol { get; set; }
        int? Callee_Port { get; set; }
        string? Callee_RelayIPAddress { get; set; }
        int? Callee_RelayPort { get; set; }
        string? Callee_DnsSuffix { get; set; }
        string? Callee_TraceRouteHops { get; set; }
        string? Callee_BSSID { get; set; }
        string? Callee_WifiRadioType { get; set; }
        string? Callee_WifiBand { get; set; }
        int? Callee_WifiChannel { get; set; }
        int? Callee_WifiSignalStrength { get; set; }
        int? Callee_WifiBatteryCharge { get; set; }
        string? Callee_WifiMicrosoftDriver { get; set; }
        string? Callee_WifiMicrosoftDriverVersion { get; set; }
        string? Callee_WifiVendorDriver { get; set; }
        string? Callee_WifiVendorDriverVersion { get; set; }
        string? Callee_CaptureDeviceName { get; set; }
        string? Callee_CaptureDeviceDriver { get; set; }
        string? Callee_RenderDeviceName { get; set; }
        string? Callee_RenderDeviceDriver { get; set; }
        double? Callee_SentSignalLevel { get; set; }
        double? Callee_SentNoiseLevel { get; set; }
        double? Callee_MicGlitchRate { get; set; }
        double? Callee_ReceivedSignalLevel { get; set; }
        double? Callee_ReceivedNoiseLevel { get; set; }
        double? Callee_SpeakerGlitchRate { get; set; }
        int? Callee_HowlingEventCount { get; set; }
        double? Callee_InitialSignalLevelRootMeanSquare { get; set; }
        double? Callee_DeviceGlitchEventRatio { get; set; }
        double? Callee_DeviceClippingEventRatio { get; set; }
        double? Callee_LowSpeechToNoiseEventRatio { get; set; }
        double? Callee_CaptureNotFunctioningEventRatio { get; set; }
        double? Callee_SentQualityEventRatio { get; set; }
        double? Callee_LowSpeechLevelEventRatio { get; set; }
        double? Callee_RenderNotFunctioningEventRatio { get; set; }
        double? Callee_ReceivedQualityEventRatio { get; set; }
        double? Callee_RenderZeroVolumeEventRatio { get; set; }
        double? Callee_RenderMuteEventRatio { get; set; }
        double? Callee_CpuInsufficentEventRatio { get; set; }
        double? Callee_DelayEventRatio { get; set; }
        double? Callee_BandwidthLowEventRatio { get; set; }
        string? Callee_FeedbackRating { get; set; }
        string? Callee_FeedbackText { get; set; }
        string? Callee_FeedbackTokens { get; set; }
        string? Caller_UserDisplayName { get; set; }
        Guid? Caller_UserId { get; set; }
        Guid? Caller_UserTenantId { get; set; }
        string? Caller_ApplicationInstanceDisplayName { get; set; }
        Guid? Caller_ApplicationInstanceId { get; set; }
        Guid? Caller_ApplicationInstanceTenantId { get; set; }
        string? Caller_GuestDisplayName { get; set; }
        Guid? Caller_GuestId { get; set; }
        Guid? Caller_GuestTenantId { get; set; }
        string? Caller_PhoneDisplayName { get; set; }
        string? Caller_PhoneId { get; set; }
        Guid? Caller_PhoneTenantId { get; set; }
        string? Caller_OnPremisesDisplayName { get; set; }
        Guid? Caller_OnPremisesId { get; set; }
        Guid? Caller_OnPremisesTenantId { get; set; }
        string? Caller_EncryptedDisplayName { get; set; }
        Guid? Caller_EncryptedId { get; set; }
        Guid? Caller_EncryptedTenantId { get; set; }
        string? Caller_AcsUserDisplayName { get; set; }
        Guid? Caller_AcsUserId { get; set; }
        Guid? Caller_AcsUserTenantId { get; set; }
        string? Caller_SpoolUserDisplayName { get; set; }
        Guid? Caller_SpoolUserId { get; set; }
        Guid? Caller_SpoolUserTenantId { get; set; }
        string? Caller_AcsApplicationInstanceDisplayName { get; set; }
        Guid? Caller_AcsApplicationInstanceId { get; set; }
        Guid? Caller_AcsApplicationInstanceTenantId { get; set; }
        string? Caller_SpoolApplicationInstanceDisplayName { get; set; }
        Guid? Caller_SpoolApplicationInstanceId { get; set; }
        Guid? Caller_SpoolApplicationInstanceTenantId { get; set; }
        string? Caller_Id { get; set; }
        string? Caller_UserPrincipalName { get; set; }
        string? Caller_DisplayName { get; set; }
        Guid? Caller_TenantId { get; set; }
        string? Caller_IdType { get; set; }
        string? Caller_EndpointType { get; set; }
        string? Caller_ProductFamily { get; set; }
        string? Caller_Platform { get; set; }
        string? Caller_UserAgentHeaderValue { get; set; }
        string? Caller_ServiceRole { get; set; }
        string? Caller_ApplicationVersion { get; set; }
        Guid? Caller_AzureAdAppId { get; set; }
        Guid? Caller_CommunicationServiceId { get; set; }
        string? Caller_ConnectionType { get; set; }
        string? Caller_ReflexiveIPAddress { get; set; }
        string? Caller_Subnet { get; set; }
        string? Caller_IpAddress { get; set; }
        string? Caller_MacAddress { get; set; }
        long? Caller_LinkSpeed { get; set; }
        string? Caller_NetworkTransportProtocol { get; set; }
        int? Caller_Port { get; set; }
        string? Caller_RelayIPAddress { get; set; }
        int? Caller_RelayPort { get; set; }
        string? Caller_DnsSuffix { get; set; }
        string? Caller_TraceRouteHops { get; set; }
        string? Caller_BSSID { get; set; }
        string? Caller_WifiRadioType { get; set; }
        string? Caller_WifiBand { get; set; }
        int? Caller_WifiChannel { get; set; }
        int? Caller_WifiSignalStrength { get; set; }
        int? Caller_WifiBatteryCharge { get; set; }
        string? Caller_WifiMicrosoftDriver { get; set; }
        string? Caller_WifiMicrosoftDriverVersion { get; set; }
        string? Caller_WifiVendorDriver { get; set; }
        string? Caller_WifiVendorDriverVersion { get; set; }
        string? Caller_CaptureDeviceName { get; set; }
        string? Caller_CaptureDeviceDriver { get; set; }
        string? Caller_RenderDeviceName { get; set; }
        string? Caller_RenderDeviceDriver { get; set; }
        double? Caller_SentSignalLevel { get; set; }
        double? Caller_SentNoiseLevel { get; set; }
        double? Caller_MicGlitchRate { get; set; }
        double? Caller_ReceivedSignalLevel { get; set; }
        double? Caller_ReceivedNoiseLevel { get; set; }
        double? Caller_SpeakerGlitchRate { get; set; }
        int? Caller_HowlingEventCount { get; set; }
        double? Caller_InitialSignalLevelRootMeanSquare { get; set; }
        double? Caller_DeviceGlitchEventRatio { get; set; }
        double? Caller_DeviceClippingEventRatio { get; set; }
        double? Caller_LowSpeechToNoiseEventRatio { get; set; }
        double? Caller_CaptureNotFunctioningEventRatio { get; set; }
        double? Caller_SentQualityEventRatio { get; set; }
        double? Caller_LowSpeechLevelEventRatio { get; set; }
        double? Caller_RenderNotFunctioningEventRatio { get; set; }
        double? Caller_ReceivedQualityEventRatio { get; set; }
        double? Caller_RenderZeroVolumeEventRatio { get; set; }
        double? Caller_RenderMuteEventRatio { get; set; }
        double? Caller_CpuInsufficentEventRatio { get; set; }
        double? Caller_DelayEventRatio { get; set; }
        double? Caller_BandwidthLowEventRatio { get; set; }
        string? Caller_FeedbackRating { get; set; }
        string? Caller_FeedbackText { get; set; }
        string? Caller_FeedbackTokens { get; set; }
    }
}