using System;

namespace CallRecordInsights.Models
{
    public class CosmosCallRecord : KustoCallRecord
    {
        private const string ROW_KEY_SEPARATOR = "_";

#pragma warning disable IDE1006 // Naming Styles -- id is a Cosmos DB reserved property
        public string id { get => GetId(); set { } }
#pragma warning restore IDE1006 // Naming Styles

        /// <summary>
        /// Gets the Cosmos id for the call record
        /// The format is <see cref="CallId"/>_<see cref="SessionId"/>_<see cref="MediaLabel"/>_<see cref="StreamId"/>_<see cref="StreamDirection"/>
        /// </summary>
        /// <returns></returns>
        private string GetId()
        {
            return $"{CallId?.ToString().Replace(ROW_KEY_SEPARATOR, string.Empty)}" +
                $"{ROW_KEY_SEPARATOR}" +
                $"{SessionId?.ToString().Replace(ROW_KEY_SEPARATOR, string.Empty)}" +
                $"{ROW_KEY_SEPARATOR}" +
                $"{MediaLabel?.Replace(ROW_KEY_SEPARATOR, string.Empty)}" +
                $"{ROW_KEY_SEPARATOR}" +
                $"{StreamId?.Replace(ROW_KEY_SEPARATOR, string.Empty)}" +
                $"{ROW_KEY_SEPARATOR}" +
                $"{StreamDirection?.Replace(ROW_KEY_SEPARATOR, string.Empty)}";
        }
        /// <summary>
        /// Creates a new instance of <see cref="CosmosCallRecord"/> from an instance of <see cref="IKustoCallRecord"/>
        /// </summary>
        /// <param name="callRecord">The <see cref="IKustoCallRecord"/> to convert</param>
        /// <returns></returns>
        /// <exception cref="ArgumentNullException">If <paramref name="callRecord"/> is null</exception>
        public static CosmosCallRecord Create(IKustoCallRecord callRecord)
        {
            var kustoCallRecord = callRecord as KustoCallRecord ?? throw new ArgumentNullException(nameof(callRecord));
            return new CosmosCallRecord
            {
                CallRecordTenantIdContext = kustoCallRecord.CallRecordTenantIdContext,
                CallId = kustoCallRecord.CallId,
                SessionId = kustoCallRecord.SessionId,
                StreamId = kustoCallRecord.StreamId,
                StreamDirection = kustoCallRecord.StreamDirection,
                MediaLabel = kustoCallRecord.MediaLabel,
                CallStartTime = kustoCallRecord.CallStartTime,
                CallEndTime = kustoCallRecord.CallEndTime,
                SessionStartTime = kustoCallRecord.SessionStartTime,
                SessionEndTime = kustoCallRecord.SessionEndTime,
                LastModifiedDateTimeOffset = kustoCallRecord.LastModifiedDateTimeOffset,
                CallType = kustoCallRecord.CallType,
                JoinWebUrl = kustoCallRecord.JoinWebUrl,
                VideoCodec = kustoCallRecord.VideoCodec,
                AudioCodec = kustoCallRecord.AudioCodec,
                WasMediaBypassed = kustoCallRecord.WasMediaBypassed,
                FailureStage = kustoCallRecord.FailureStage,
                FailureReason = kustoCallRecord.FailureReason,
                PacketUtilization = kustoCallRecord.PacketUtilization,
                AverageBandwidthEstimate = kustoCallRecord.AverageBandwidthEstimate,
                AverageJitter = kustoCallRecord.AverageJitter,
                MaxJitter = kustoCallRecord.MaxJitter,
                AverageRoundTripTime = kustoCallRecord.AverageRoundTripTime,
                MaxRoundTripTime = kustoCallRecord.MaxRoundTripTime,
                AverageAudioNetworkJitter = kustoCallRecord.AverageAudioNetworkJitter,
                MaxAudioNetworkJitter = kustoCallRecord.MaxAudioNetworkJitter,
                AverageAudioDegradation = kustoCallRecord.AverageAudioDegradation,
                AveragePacketLossRate = kustoCallRecord.AveragePacketLossRate,
                MaxPacketLossRate = kustoCallRecord.MaxPacketLossRate,
                PostForwardErrorCorrectionPacketLossRate = kustoCallRecord.PostForwardErrorCorrectionPacketLossRate,
                AverageRatioOfConcealedSamples = kustoCallRecord.AverageRatioOfConcealedSamples,
                MaxRatioOfConcealedSamples = kustoCallRecord.MaxRatioOfConcealedSamples,
                LowVideoProcessingCapabilityRatio = kustoCallRecord.LowVideoProcessingCapabilityRatio,
                AverageVideoFrameRate = kustoCallRecord.AverageVideoFrameRate,
                AverageReceivedFrameRate = kustoCallRecord.AverageReceivedFrameRate,
                LowFrameRateRatio = kustoCallRecord.LowFrameRateRatio,
                AverageVideoPacketLossRate = kustoCallRecord.AverageVideoPacketLossRate,
                AverageVideoFrameLossPercentage = kustoCallRecord.AverageVideoFrameLossPercentage,

                Organizer_UserDisplayName = kustoCallRecord.Organizer_UserDisplayName,
                Organizer_UserId = kustoCallRecord.Organizer_UserId,
                Organizer_UserTenantId = kustoCallRecord.Organizer_UserTenantId,
                Organizer_ApplicationInstanceDisplayName = kustoCallRecord.Organizer_ApplicationInstanceDisplayName,
                Organizer_ApplicationInstanceId = kustoCallRecord.Organizer_ApplicationInstanceId,
                Organizer_ApplicationInstanceTenantId = kustoCallRecord.Organizer_ApplicationInstanceTenantId,
                Organizer_GuestDisplayName = kustoCallRecord.Organizer_GuestDisplayName,
                Organizer_GuestId = kustoCallRecord.Organizer_GuestId,
                Organizer_GuestTenantId = kustoCallRecord.Organizer_GuestTenantId,
                Organizer_PhoneDisplayName = kustoCallRecord.Organizer_PhoneDisplayName,
                Organizer_PhoneId = kustoCallRecord.Organizer_PhoneId,
                Organizer_PhoneTenantId = kustoCallRecord.Organizer_PhoneTenantId,
                Organizer_OnPremisesDisplayName = kustoCallRecord.Organizer_OnPremisesDisplayName,
                Organizer_OnPremisesId = kustoCallRecord.Organizer_OnPremisesId,
                Organizer_OnPremisesTenantId = kustoCallRecord.Organizer_OnPremisesTenantId,
                Organizer_EncryptedDisplayName = kustoCallRecord.Organizer_EncryptedDisplayName,
                Organizer_EncryptedId = kustoCallRecord.Organizer_EncryptedId,
                Organizer_EncryptedTenantId = kustoCallRecord.Organizer_EncryptedTenantId,
                Organizer_AcsUserDisplayName = kustoCallRecord.Organizer_AcsUserDisplayName,
                Organizer_AcsUserId = kustoCallRecord.Organizer_AcsUserId,
                Organizer_AcsUserTenantId = kustoCallRecord.Organizer_AcsUserTenantId,
                Organizer_SpoolUserDisplayName = kustoCallRecord.Organizer_SpoolUserDisplayName,
                Organizer_SpoolUserId = kustoCallRecord.Organizer_SpoolUserId,
                Organizer_SpoolUserTenantId = kustoCallRecord.Organizer_SpoolUserTenantId,
                Organizer_AcsApplicationInstanceDisplayName = kustoCallRecord.Organizer_AcsApplicationInstanceDisplayName,
                Organizer_AcsApplicationInstanceId = kustoCallRecord.Organizer_AcsApplicationInstanceId,
                Organizer_AcsApplicationInstanceTenantId = kustoCallRecord.Organizer_AcsApplicationInstanceTenantId,
                Organizer_SpoolApplicationInstanceDisplayName = kustoCallRecord.Organizer_SpoolApplicationInstanceDisplayName,
                Organizer_SpoolApplicationInstanceId = kustoCallRecord.Organizer_SpoolApplicationInstanceId,
                Organizer_SpoolApplicationInstanceTenantId = kustoCallRecord.Organizer_SpoolApplicationInstanceTenantId,
                Organizer_Id = kustoCallRecord.Organizer_Id,
                Organizer_DisplayName = kustoCallRecord.Organizer_DisplayName,
                Organizer_UserPrincipalName = kustoCallRecord.Organizer_UserPrincipalName,
                Organizer_TenantId = kustoCallRecord.Organizer_TenantId,
                Organizer_IdType = kustoCallRecord.Organizer_IdType,

                Callee_UserDisplayName = kustoCallRecord.Callee_UserDisplayName,
                Callee_UserId = kustoCallRecord.Callee_UserId,
                Callee_UserTenantId = kustoCallRecord.Callee_UserTenantId,
                Callee_ApplicationInstanceDisplayName = kustoCallRecord.Callee_ApplicationInstanceDisplayName,
                Callee_ApplicationInstanceId = kustoCallRecord.Callee_ApplicationInstanceId,
                Callee_ApplicationInstanceTenantId = kustoCallRecord.Callee_ApplicationInstanceTenantId,
                Callee_GuestDisplayName = kustoCallRecord.Callee_GuestDisplayName,
                Callee_GuestId = kustoCallRecord.Callee_GuestId,
                Callee_GuestTenantId = kustoCallRecord.Callee_GuestTenantId,
                Callee_PhoneDisplayName = kustoCallRecord.Callee_PhoneDisplayName,
                Callee_PhoneId = kustoCallRecord.Callee_PhoneId,
                Callee_PhoneTenantId = kustoCallRecord.Callee_PhoneTenantId,
                Callee_OnPremisesDisplayName = kustoCallRecord.Callee_OnPremisesDisplayName,
                Callee_OnPremisesId = kustoCallRecord.Callee_OnPremisesId,
                Callee_OnPremisesTenantId = kustoCallRecord.Callee_OnPremisesTenantId,
                Callee_EncryptedDisplayName = kustoCallRecord.Callee_EncryptedDisplayName,
                Callee_EncryptedId = kustoCallRecord.Callee_EncryptedId,
                Callee_EncryptedTenantId = kustoCallRecord.Callee_EncryptedTenantId,
                Callee_AcsUserDisplayName = kustoCallRecord.Callee_AcsUserDisplayName,
                Callee_AcsUserId = kustoCallRecord.Callee_AcsUserId,
                Callee_AcsUserTenantId = kustoCallRecord.Callee_AcsUserTenantId,
                Callee_SpoolUserDisplayName = kustoCallRecord.Callee_SpoolUserDisplayName,
                Callee_SpoolUserId = kustoCallRecord.Callee_SpoolUserId,
                Callee_SpoolUserTenantId = kustoCallRecord.Callee_SpoolUserTenantId,
                Callee_AcsApplicationInstanceDisplayName = kustoCallRecord.Callee_AcsApplicationInstanceDisplayName,
                Callee_AcsApplicationInstanceId = kustoCallRecord.Callee_AcsApplicationInstanceId,
                Callee_AcsApplicationInstanceTenantId = kustoCallRecord.Callee_AcsApplicationInstanceTenantId,
                Callee_SpoolApplicationInstanceDisplayName = kustoCallRecord.Callee_SpoolApplicationInstanceDisplayName,
                Callee_SpoolApplicationInstanceId = kustoCallRecord.Callee_SpoolApplicationInstanceId,
                Callee_SpoolApplicationInstanceTenantId = kustoCallRecord.Callee_SpoolApplicationInstanceTenantId,
                Callee_Id = kustoCallRecord.Callee_Id,
                Callee_DisplayName = kustoCallRecord.Callee_DisplayName,
                Callee_UserPrincipalName = kustoCallRecord.Callee_UserPrincipalName,
                Callee_TenantId = kustoCallRecord.Callee_TenantId,
                Callee_IdType = kustoCallRecord.Callee_IdType,
                Callee_EndpointType = kustoCallRecord.Callee_EndpointType,
                Callee_ProductFamily = kustoCallRecord.Callee_ProductFamily,
                Callee_Platform = kustoCallRecord.Callee_Platform,
                Callee_UserAgentHeaderValue = kustoCallRecord.Callee_UserAgentHeaderValue,
                Callee_ServiceRole = kustoCallRecord.Callee_ServiceRole,
                Callee_ApplicationVersion = kustoCallRecord.Callee_ApplicationVersion,
                Callee_AzureAdAppId = kustoCallRecord.Callee_AzureAdAppId,
                Callee_CommunicationServiceId = kustoCallRecord.Callee_CommunicationServiceId,
                Callee_ConnectionType = kustoCallRecord.Callee_ConnectionType,
                Callee_ReflexiveIPAddress = kustoCallRecord.Callee_ReflexiveIPAddress,
                Callee_Subnet = kustoCallRecord.Callee_Subnet,
                Callee_IpAddress = kustoCallRecord.Callee_IpAddress,
                Callee_MacAddress = kustoCallRecord.Callee_MacAddress,
                Callee_LinkSpeed = kustoCallRecord.Callee_LinkSpeed,
                Callee_NetworkTransportProtocol = kustoCallRecord.Callee_NetworkTransportProtocol,
                Callee_Port = kustoCallRecord.Callee_Port,
                Callee_RelayIPAddress = kustoCallRecord.Callee_RelayIPAddress,
                Callee_RelayPort = kustoCallRecord.Callee_RelayPort,
                Callee_DnsSuffix = kustoCallRecord.Callee_DnsSuffix,
                Callee_TraceRouteHops = kustoCallRecord.Callee_TraceRouteHops,
                Callee_BSSID = kustoCallRecord.Callee_BSSID,
                Callee_WifiRadioType = kustoCallRecord.Callee_WifiRadioType,
                Callee_WifiBand = kustoCallRecord.Callee_WifiBand,
                Callee_WifiChannel = kustoCallRecord.Callee_WifiChannel,
                Callee_WifiSignalStrength = kustoCallRecord.Callee_WifiSignalStrength,
                Callee_WifiBatteryCharge = kustoCallRecord.Callee_WifiBatteryCharge,
                Callee_WifiMicrosoftDriver = kustoCallRecord.Callee_WifiMicrosoftDriver,
                Callee_WifiMicrosoftDriverVersion = kustoCallRecord.Callee_WifiMicrosoftDriverVersion,
                Callee_WifiVendorDriver = kustoCallRecord.Callee_WifiVendorDriver,
                Callee_WifiVendorDriverVersion = kustoCallRecord.Callee_WifiVendorDriverVersion,
                Callee_CaptureDeviceName = kustoCallRecord.Callee_CaptureDeviceName,
                Callee_CaptureDeviceDriver = kustoCallRecord.Callee_CaptureDeviceDriver,
                Callee_RenderDeviceName = kustoCallRecord.Callee_RenderDeviceName,
                Callee_RenderDeviceDriver = kustoCallRecord.Callee_RenderDeviceDriver,
                Callee_SentSignalLevel = kustoCallRecord.Callee_SentSignalLevel,
                Callee_SentNoiseLevel = kustoCallRecord.Callee_SentNoiseLevel,
                Callee_MicGlitchRate = kustoCallRecord.Callee_MicGlitchRate,
                Callee_ReceivedSignalLevel = kustoCallRecord.Callee_ReceivedSignalLevel,
                Callee_ReceivedNoiseLevel = kustoCallRecord.Callee_ReceivedNoiseLevel,
                Callee_SpeakerGlitchRate = kustoCallRecord.Callee_SpeakerGlitchRate,
                Callee_HowlingEventCount = kustoCallRecord.Callee_HowlingEventCount,
                Callee_InitialSignalLevelRootMeanSquare = kustoCallRecord.Callee_InitialSignalLevelRootMeanSquare,
                Callee_DeviceGlitchEventRatio = kustoCallRecord.Callee_DeviceGlitchEventRatio,
                Callee_DeviceClippingEventRatio = kustoCallRecord.Callee_DeviceClippingEventRatio,
                Callee_LowSpeechToNoiseEventRatio = kustoCallRecord.Callee_LowSpeechToNoiseEventRatio,
                Callee_CaptureNotFunctioningEventRatio = kustoCallRecord.Callee_CaptureNotFunctioningEventRatio,
                Callee_SentQualityEventRatio = kustoCallRecord.Callee_SentQualityEventRatio,
                Callee_LowSpeechLevelEventRatio = kustoCallRecord.Callee_LowSpeechLevelEventRatio,
                Callee_RenderNotFunctioningEventRatio = kustoCallRecord.Callee_RenderNotFunctioningEventRatio,
                Callee_ReceivedQualityEventRatio = kustoCallRecord.Callee_ReceivedQualityEventRatio,
                Callee_RenderZeroVolumeEventRatio = kustoCallRecord.Callee_RenderZeroVolumeEventRatio,
                Callee_RenderMuteEventRatio = kustoCallRecord.Callee_RenderMuteEventRatio,
                Callee_CpuInsufficentEventRatio = kustoCallRecord.Callee_CpuInsufficentEventRatio,
                Callee_DelayEventRatio = kustoCallRecord.Callee_DelayEventRatio,
                Callee_BandwidthLowEventRatio = kustoCallRecord.Callee_BandwidthLowEventRatio,
                Callee_FeedbackRating = kustoCallRecord.Callee_FeedbackRating,
                Callee_FeedbackText = kustoCallRecord.Callee_FeedbackText,
                Callee_FeedbackTokens = kustoCallRecord.Callee_FeedbackTokens,
                Caller_UserDisplayName = kustoCallRecord.Caller_UserDisplayName,
                Caller_UserId = kustoCallRecord.Caller_UserId,
                Caller_UserTenantId = kustoCallRecord.Caller_UserTenantId,
                Caller_ApplicationInstanceDisplayName = kustoCallRecord.Caller_ApplicationInstanceDisplayName,
                Caller_ApplicationInstanceId = kustoCallRecord.Caller_ApplicationInstanceId,
                Caller_ApplicationInstanceTenantId = kustoCallRecord.Caller_ApplicationInstanceTenantId,
                Caller_GuestDisplayName = kustoCallRecord.Caller_GuestDisplayName,
                Caller_GuestId = kustoCallRecord.Caller_GuestId,
                Caller_GuestTenantId = kustoCallRecord.Caller_GuestTenantId,
                Caller_PhoneDisplayName = kustoCallRecord.Caller_PhoneDisplayName,
                Caller_PhoneId = kustoCallRecord.Caller_PhoneId,
                Caller_PhoneTenantId = kustoCallRecord.Caller_PhoneTenantId,
                Caller_OnPremisesDisplayName = kustoCallRecord.Caller_OnPremisesDisplayName,
                Caller_OnPremisesId = kustoCallRecord.Caller_OnPremisesId,
                Caller_OnPremisesTenantId = kustoCallRecord.Caller_OnPremisesTenantId,
                Caller_EncryptedDisplayName = kustoCallRecord.Caller_EncryptedDisplayName,
                Caller_EncryptedId = kustoCallRecord.Caller_EncryptedId,
                Caller_EncryptedTenantId = kustoCallRecord.Caller_EncryptedTenantId,
                Caller_AcsUserDisplayName = kustoCallRecord.Caller_AcsUserDisplayName,
                Caller_AcsUserId = kustoCallRecord.Caller_AcsUserId,
                Caller_AcsUserTenantId = kustoCallRecord.Caller_AcsUserTenantId,
                Caller_SpoolUserDisplayName = kustoCallRecord.Caller_SpoolUserDisplayName,
                Caller_SpoolUserId = kustoCallRecord.Caller_SpoolUserId,
                Caller_SpoolUserTenantId = kustoCallRecord.Caller_SpoolUserTenantId,
                Caller_AcsApplicationInstanceDisplayName = kustoCallRecord.Caller_AcsApplicationInstanceDisplayName,
                Caller_AcsApplicationInstanceId = kustoCallRecord.Caller_AcsApplicationInstanceId,
                Caller_AcsApplicationInstanceTenantId = kustoCallRecord.Caller_AcsApplicationInstanceTenantId,
                Caller_SpoolApplicationInstanceDisplayName = kustoCallRecord.Caller_SpoolApplicationInstanceDisplayName,
                Caller_SpoolApplicationInstanceId = kustoCallRecord.Caller_SpoolApplicationInstanceId,
                Caller_SpoolApplicationInstanceTenantId = kustoCallRecord.Caller_SpoolApplicationInstanceTenantId,

                Caller_Id = kustoCallRecord.Caller_Id,
                Caller_DisplayName = kustoCallRecord.Caller_DisplayName,
                Caller_UserPrincipalName = kustoCallRecord.Caller_UserPrincipalName,
                Caller_TenantId = kustoCallRecord.Caller_TenantId,
                Caller_IdType = kustoCallRecord.Caller_IdType,
                Caller_EndpointType = kustoCallRecord.Caller_EndpointType,
                Caller_ProductFamily = kustoCallRecord.Caller_ProductFamily,
                Caller_Platform = kustoCallRecord.Caller_Platform,
                Caller_UserAgentHeaderValue = kustoCallRecord.Caller_UserAgentHeaderValue,
                Caller_ServiceRole = kustoCallRecord.Caller_ServiceRole,
                Caller_ApplicationVersion = kustoCallRecord.Caller_ApplicationVersion,
                Caller_AzureAdAppId = kustoCallRecord.Caller_AzureAdAppId,
                Caller_CommunicationServiceId = kustoCallRecord.Caller_CommunicationServiceId,
                Caller_ConnectionType = kustoCallRecord.Caller_ConnectionType,
                Caller_ReflexiveIPAddress = kustoCallRecord.Caller_ReflexiveIPAddress,
                Caller_Subnet = kustoCallRecord.Caller_Subnet,
                Caller_IpAddress = kustoCallRecord.Caller_IpAddress,
                Caller_MacAddress = kustoCallRecord.Caller_MacAddress,
                Caller_LinkSpeed = kustoCallRecord.Caller_LinkSpeed,
                Caller_NetworkTransportProtocol = kustoCallRecord.Caller_NetworkTransportProtocol,
                Caller_Port = kustoCallRecord.Caller_Port,
                Caller_RelayIPAddress = kustoCallRecord.Caller_RelayIPAddress,
                Caller_RelayPort = kustoCallRecord.Caller_RelayPort,
                Caller_DnsSuffix = kustoCallRecord.Caller_DnsSuffix,
                Caller_TraceRouteHops = kustoCallRecord.Caller_TraceRouteHops,
                Caller_BSSID = kustoCallRecord.Caller_BSSID,
                Caller_WifiRadioType = kustoCallRecord.Caller_WifiRadioType,
                Caller_WifiBand = kustoCallRecord.Caller_WifiBand,
                Caller_WifiChannel = kustoCallRecord.Caller_WifiChannel,
                Caller_WifiSignalStrength = kustoCallRecord.Caller_WifiSignalStrength,
                Caller_WifiBatteryCharge = kustoCallRecord.Caller_WifiBatteryCharge,
                Caller_WifiMicrosoftDriver = kustoCallRecord.Caller_WifiMicrosoftDriver,
                Caller_WifiMicrosoftDriverVersion = kustoCallRecord.Caller_WifiMicrosoftDriverVersion,
                Caller_WifiVendorDriver = kustoCallRecord.Caller_WifiVendorDriver,
                Caller_WifiVendorDriverVersion = kustoCallRecord.Caller_WifiVendorDriverVersion,
                Caller_CaptureDeviceName = kustoCallRecord.Caller_CaptureDeviceName,
                Caller_CaptureDeviceDriver = kustoCallRecord.Caller_CaptureDeviceDriver,
                Caller_RenderDeviceName = kustoCallRecord.Caller_RenderDeviceName,
                Caller_RenderDeviceDriver = kustoCallRecord.Caller_RenderDeviceDriver,
                Caller_SentSignalLevel = kustoCallRecord.Caller_SentSignalLevel,
                Caller_SentNoiseLevel = kustoCallRecord.Caller_SentNoiseLevel,
                Caller_MicGlitchRate = kustoCallRecord.Caller_MicGlitchRate,
                Caller_ReceivedSignalLevel = kustoCallRecord.Caller_ReceivedSignalLevel,
                Caller_ReceivedNoiseLevel = kustoCallRecord.Caller_ReceivedNoiseLevel,
                Caller_SpeakerGlitchRate = kustoCallRecord.Caller_SpeakerGlitchRate,
                Caller_HowlingEventCount = kustoCallRecord.Caller_HowlingEventCount,
                Caller_InitialSignalLevelRootMeanSquare = kustoCallRecord.Caller_InitialSignalLevelRootMeanSquare,
                Caller_DeviceGlitchEventRatio = kustoCallRecord.Caller_DeviceGlitchEventRatio,
                Caller_DeviceClippingEventRatio = kustoCallRecord.Caller_DeviceClippingEventRatio,
                Caller_LowSpeechToNoiseEventRatio = kustoCallRecord.Caller_LowSpeechToNoiseEventRatio,
                Caller_CaptureNotFunctioningEventRatio = kustoCallRecord.Caller_CaptureNotFunctioningEventRatio,
                Caller_SentQualityEventRatio = kustoCallRecord.Caller_SentQualityEventRatio,
                Caller_LowSpeechLevelEventRatio = kustoCallRecord.Caller_LowSpeechLevelEventRatio,
                Caller_RenderNotFunctioningEventRatio = kustoCallRecord.Caller_RenderNotFunctioningEventRatio,
                Caller_ReceivedQualityEventRatio = kustoCallRecord.Caller_ReceivedQualityEventRatio,
                Caller_RenderZeroVolumeEventRatio = kustoCallRecord.Caller_RenderZeroVolumeEventRatio,
                Caller_RenderMuteEventRatio = kustoCallRecord.Caller_RenderMuteEventRatio,
                Caller_CpuInsufficentEventRatio = kustoCallRecord.Caller_CpuInsufficentEventRatio,
                Caller_DelayEventRatio = kustoCallRecord.Caller_DelayEventRatio,
                Caller_BandwidthLowEventRatio = kustoCallRecord.Caller_BandwidthLowEventRatio,
                Caller_FeedbackRating = kustoCallRecord.Caller_FeedbackRating,
                Caller_FeedbackText = kustoCallRecord.Caller_FeedbackText,
                Caller_FeedbackTokens = kustoCallRecord.Caller_FeedbackTokens,
            };
        }
    }
}
